spring:
  application:
    name: todolist-version-3

  datasource:
    url: jdbc:mysql://localhost:3306/todolist_v3
    username: root
    password: phamthang20042005

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    root: INFO
    com.myapp: DEBUG

# Swagger (springdoc-openapi)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

open:
  api:
    title: API Document
    version: v1.0.0
    description: Description of API Service
    serverUrl: http://localhost:8080
    serverName: server test